import { useEffect, useState } from 'react'
import { ArrowRight, ChevronLeft, ChevronRight, Menu, Package, ShieldCheck, Sparkles, Truck, X } from 'lucide-react'
import { FaFacebookF, FaInstagram, FaLinkedinIn, FaPinterestP, FaSnapchatGhost, FaWhatsapp, FaYoutube } from 'react-icons/fa'
import { SiGmail, SiX } from 'react-icons/si'
import { assets, categories, products } from './data'
import './App.css'

const money = value => `₹${value.toLocaleString('en-IN')}`

function Reveal({ children, className = '' }) { return <div className={`reveal ${className}`}>{children}</div> }

const instagramUrl = 'https://www.instagram.com/theirayajewels/'

function Header({ openMenu, setOpenMenu }) {
  const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 30); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  return <>
    <div className="announcement">FREE DELIVERY ON ORDERS ₹999+ <span>•</span> ANTI-TARNISH JEWELLERY <span>•</span> MADE FOR EVERYDAY</div>
    <header className={`site-header ${scrolled ? 'is-scrolled' : ''}`}>
      <button className="icon-button mobile-only" aria-label="Open menu" onClick={() => setOpenMenu(true)}><Menu /></button>
      <a className="brand" href="#top" aria-label="Iraya Jewels home"><img src={assets.logoImage} alt="IRAYA JEWELS" /></a>
      <a className="join-button" href={instagramUrl} target="_blank" rel="noreferrer"><FaInstagram /> <span>Join Iraya</span></a>
    </header>
    {openMenu && <aside className="mobile-drawer"><div className="drawer-head"><img src={assets.logoImage} alt="IRAYA JEWELS" /><button className="icon-button" onClick={() => setOpenMenu(false)} aria-label="Close menu"><X /></button></div><div className="drawer-links"><a href="#shop" onClick={() => setOpenMenu(false)}>Shop the collection <ArrowRight /></a><a href="#coming-soon" onClick={() => setOpenMenu(false)}>Play Store app <ArrowRight /></a></div><p>Everyday jewellery, but make it aesthetic.</p></aside>}
  </>
}

function Hero() { return <section className="hero" id="top"><img className="hero-image" src={assets.heroImage} alt="Woman styling layered gold jewellery" /><div className="hero-shade" /><div className="hero-copy"><p className="eyebrow">EVERYDAY JEWELLERY, BUT MAKE IT AESTHETIC.</p><h1>Jewellery for<br /><em>your every mood.</em></h1><p className="hero-subtitle">Modern pieces designed to make every outfit feel a little more you.</p><div className="hero-actions">
  {/* <a className="button button-primary" href="#coming-soon">Shop the collection <ArrowRight /></a> */}
  </div></div></section> }

function Benefits() { const items = [[Sparkles, '316L STAINLESS STEEL', 'Premium-grade, made to last'], [ShieldCheck, 'ANTI-TARNISH', 'Made for everyday wear'], [Sparkles, 'CZ DIAMONDS', 'Brilliant crystal detailing'], [Truck, 'FREE DELIVERY', 'On orders ₹999+']]; return <section className="benefits">{items.map(([Icon, title, copy]) => <div key={title}><Icon /><strong>{title}</strong><span>{copy}</span></div>)}</section> }

function Categories() { return <section className="section categories" id="shop"><Reveal><p className="eyebrow">SHOP YOUR STYLE</p><h2>Find your perfect piece</h2></Reveal><div className="category-grid">{categories.map(category => <a href="#bestsellers" className="category-card" key={category.name}><img src={category.image} alt={category.name} loading="lazy" /><div><h3>{category.name}</h3></div></a>)}</div></section> }

function ProductCard({ product }) { const discount = Math.round((1 - product.price / product.mrp) * 100); return <article className="product-card"><div className="product-image"><img src={product.image} alt={product.name} loading="lazy" />{product.badge && <span className="product-badge">{product.badge}</span>}</div><div className="product-info"><div className="product-rating">★★★★★ <span>({product.reviews})</span></div><h3>{product.name}</h3><div className="price"><strong>{money(product.price)}</strong><del>{money(product.mrp)}</del><span>{discount}% off</span></div></div></article> }

// function Products() { const [offset, setOffset] = useState(0); const visible = products.slice(offset, offset + 4); return <section className="section products-section" id="bestsellers"><Reveal><p className="eyebrow">THE EDIT</p><h2>The ones everyone's loving</h2><p className="section-subtitle">Your everyday favourites, made to stay.</p></Reveal><div className="product-carousel"><button className="carousel-arrow" onClick={() => setOffset(Math.max(0, offset - 1))} aria-label="Previous products"><ChevronLeft /></button><div className="product-grid">{visible.map(product => <ProductCard key={product.id} product={product} />)}</div><button className="carousel-arrow" onClick={() => setOffset(Math.min(products.length - 4, offset + 1))} aria-label="Next products"><ChevronRight /></button></div><a href="#shop" className="under-link">View all pieces <ArrowRight /></a></section> }

function Story() { return <><section className="story"><div className="story-image"><img src={assets.handImage} alt="Hands wearing delicate rings" loading="lazy" /></div><div className="story-copy"><p className="eyebrow">OUR POINT OF VIEW</p><h2>Jewellery that<br /><em>feels like you.</em></h2><p>IRAYA JEWELS was created for the moments in between — coffee dates, college days, dinner plans, spontaneous plans and everything that makes everyday life yours.</p><p>Thoughtfully designed jewellery that lets you express your style without trying too hard.</p></div></section><section className="everyday"><div><p className="eyebrow">THE IRAYA STANDARD</p><h2>Made for everyday.<br /><em>Made to last.</em></h2><div className="standard-list"><span>316L stainless steel</span><span>Anti-tarnish finish</span><span>Everyday-friendly designs</span><span>CZ crystal detailing</span></div></div><img src={assets.lifestyleImage} alt="Iraya jewellery styled with soft neutral fashion" loading="lazy" /></section></> }

// function Packaging() { return <section className="packaging"><div className="packaging-copy"><p className="eyebrow">A LITTLE RITUAL</p><h2>A little something<br /><em>to unwrap.</em></h2><p>Because receiving jewellery should feel just as special as wearing it.</p><a className="button button-dark" href="#coming-soon">Shop Iraya <ArrowRight /></a></div><div className="packaging-image"><img src={assets.heroImage} alt="Iraya jewellery gifting moment" loading="lazy" /></div></section> }

function SocialAndNewsletter() { return <><section className="social section"><Reveal><p className="eyebrow">FOLLOW THE IRAYA MOOD</p><h2>Jewellery, outfits & everyday inspiration.</h2></Reveal><div className="social-grid">{[assets.oceanImage, assets.eveningImage, assets.multipleJewelleryImage, assets.headerImage, assets.elegantModelImage, assets.girlShowingImage].map((image, index) => <a href={instagramUrl} target="_blank" rel="noreferrer" key={index}><img src={image} alt="Iraya jewellery inspiration" loading="lazy" /></a>)}</div><a className="under-link" href={instagramUrl} target="_blank" rel="noreferrer">@theirayajewels <ArrowRight /></a></section><section className="newsletter"><div><p className="eyebrow">STAY IN THE LOOP</p><h2>Join the Iraya circle.</h2><p>New drops, exclusive offers and jewellery you'll want to wear on repeat.</p></div><a className="button button-primary" href={instagramUrl} target="_blank" rel="noreferrer"><FaInstagram /> Follow on Instagram</a></section></> }

function Footer() { const socials = [[FaInstagram, 'Instagram', instagramUrl], [SiGmail, 'Gmail', 'mailto:the.iraya.jewels@gmail.com'], [FaFacebookF, 'Facebook', '#top'], [FaPinterestP, 'Pinterest', '#top'], [SiX, 'X', '#top'], [FaYoutube, 'YouTube', '#top'], [FaSnapchatGhost, 'Snapchat', '#top'], [FaLinkedinIn, 'LinkedIn', '#top'], [FaWhatsapp, 'WhatsApp Business', '#top']]; return <footer><div className="footer-brand"><img src={assets.logoImage} alt="IRAYA JEWELS" /><p>Everyday jewellery,<br />but make it aesthetic.</p><div className="social-icons">{socials.map(([Icon, label, href]) => <a href={href} target={href.startsWith('http') ? '_blank' : undefined} rel={href.startsWith('http') ? 'noreferrer' : undefined} aria-label={label} title={label} key={label}><Icon /></a>)}</div></div><div className="footer-links"><div><strong>Help</strong><a href="mailto:the.iraya.jewels@gmail.com">Contact us</a><a href="#terms">T&amp;C</a><a href="#faqs">FAQs</a></div><div><strong>About</strong><a href={instagramUrl} target="_blank" rel="noreferrer">Our story</a><a href="#care">Jewellery care</a><a href="#privacy">Privacy policy</a></div></div><div className="footer-bottom"><span>© 2026 IRAYA JEWELS. All rights reserved.</span><span>Made for your every mood.</span></div></footer> }

function InfoPage({ eyebrow, title, children, image }) { return <main className="info-page"><a className="info-logo" href="#top"><img src={assets.logoImage} alt="IRAYA JEWELS" /></a><div className="info-layout"><div className="info-copy"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children}<a className="back-link" href="#top">Back to Iraya <ArrowRight /></a></div>{image && <div className="info-image"><img src={image} alt="Iraya jewellery" /></div>}</div></main> }

function TermsPage() { return <InfoPage eyebrow="THE FINE PRINT" title="Terms & conditions" image={assets.headerImage}><p>These terms keep every Iraya order clear, fair and easy to enjoy. By placing an order, you agree to provide accurate delivery details and to use our products as intended.</p><div className="info-list"><div><strong>Orders</strong><span>Orders are confirmed after payment. We may contact you if any detail needs clarification.</span></div><div><strong>Payments & delivery</strong><span>Prices are shown in Indian rupees. Delivery timelines may vary by location and courier availability.</span></div><div><strong>Returns</strong><span>Unused items in their original packaging can be requested for return within the applicable return window.</span></div></div></InfoPage> }

function PrivacyPage() { return <InfoPage eyebrow="YOUR TRUST MATTERS" title="Privacy policy" image={assets.eveningImage}><p>Iraya Jewels respects your privacy. We collect only the details needed to process orders, provide support and improve your shopping experience.</p><div className="info-list"><div><strong>What we use</strong><span>Your contact, address and order details help us fulfil deliveries and answer questions.</span></div><div><strong>What we protect</strong><span>We do not sell your personal information. Payment details are handled by secure payment partners.</span></div><div><strong>Your choices</strong><span>For privacy questions or requests, email the.iraya.jewels@gmail.com.</span></div></div></InfoPage> }

function CarePage() { return <InfoPage eyebrow="KEEP THE SPARKLE" title="Jewellery care" image={assets.pendantImage}><p>Your Iraya pieces are made for everyday wear. A little care helps them stay bright and beautiful for longer.</p><div className="info-list"><div><strong>Keep it dry</strong><span>Remove jewellery before showering, swimming or exercising, and keep it away from perfumes and creams.</span></div><div><strong>Store it softly</strong><span>Wipe each piece with a soft, dry cloth and store it separately in a cool, dry place.</span></div><div><strong>Wear it often</strong><span>316L stainless steel and anti-tarnish finishes are designed for everyday life, with gentle care.</span></div></div></InfoPage> }

function FaqPage() { const faqs = [['How do I care for my jewellery?', 'Keep pieces dry, wipe them gently after wearing and store them separately.'], ['How long does delivery take?', 'Delivery times depend on your location and are shared at checkout.'], ['How can I contact Iraya?', 'Write to the.iraya.jewels@gmail.com and our team will help you.'], ['Are the pieces suitable for everyday wear?', 'Yes. Our jewellery is made with 316L stainless steel and an anti-tarnish finish.']]; return <InfoPage eyebrow="WE ARE HERE TO HELP" title="Frequently asked questions" image={assets.oceanImage}><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronRight /></summary><p>{answer}</p></details>)}</div></InfoPage> }

function ComingSoon() { return <main className="coming-soon"><a className="coming-soon-logo" href="#top"><img src={assets.logoImage} alt="IRAYA JEWELS" /></a><div className="coming-soon-art"><img src={assets.heroImage} alt="Iraya jewellery collection" /></div><div className="coming-soon-copy"><p className="eyebrow">THE IRAYA APP</p><h1>Something beautiful<br /><em>is on its way.</em></h1><p>Our Play Store app is coming soon, with your favourite everyday pieces just a tap away.</p><a className="button button-primary" href="https://play.google.com/store" target="_blank" rel="noreferrer">Visit Play Store <ArrowRight /></a><a className="back-link" href="#top">Back to Iraya <ArrowRight /></a></div></main> }

function App() { const [openMenu, setOpenMenu] = useState(false); const [route, setRoute] = useState(window.location.hash); useEffect(() => { const onHashChange = () => { setRoute(window.location.hash); setOpenMenu(false); window.scrollTo(0, 0) }; window.addEventListener('hashchange', onHashChange); document.title = route === '#coming-soon' ? 'Coming Soon | IRAYA JEWELS' : route === '#terms' ? 'Terms & Conditions | IRAYA JEWELS' : route === '#faqs' ? 'FAQs | IRAYA JEWELS' : route === '#privacy' ? 'Privacy Policy | IRAYA JEWELS' : route === '#care' ? 'Jewellery Care | IRAYA JEWELS' : 'IRAYA JEWELS | Everyday Jewellery, But Make It Aesthetic'; return () => window.removeEventListener('hashchange', onHashChange) }, [route]); if (route === '#coming-soon') return <ComingSoon />; if (route === '#terms') return <TermsPage />; if (route === '#faqs') return <FaqPage />; if (route === '#privacy') return <PrivacyPage />; if (route === '#care') return <CarePage />; return <><Header openMenu={openMenu} setOpenMenu={setOpenMenu} /><main><Hero /><Benefits /><Categories /><Story />{/* <Products /><Packaging /> */}<SocialAndNewsletter /></main><Footer /></> }

export default App
